CREATE TABLE items (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    barcode VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    date_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT NULL,
    sold BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
